const menu = [
  {
    id: "1",
    pid: "0",
    icon: "shujukanban",
    path: "",
    label: "综合看板",
    component: "layout",
    isleaf: false,
  },
  {
    id: "1-1",
    pid: "1",
    icon: "",
    path: "/",
    label: "监控看板",
    component: "home",
    isleaf: true,
    index: true,
  },
  {
    id: "1-2",
    pid: "1",
    icon: "",
    path: "/homeReal",
    label: "实时数据",
    component: "home-real",
    isleaf: true,
  },
  {
    id: "1-3",
    pid: "1",
    icon: "",
    path: "/homeView",
    label: "数据资源",
    component: "home-view",
    isleaf: true,
  },
  {
    id: "2",
    pid: "0",
    path: "",
    label: "数据查询",
    component: "layout",
    icon: "shuju",
    isleaf: false,
  },
  {
    id: "2-1",
    pid: "2",
    icon: "",
    path: "/dataList",
    component: "data-list",
    label: "监测数据",
    isleaf: true,
  },
  {
    id: "2-2",
    pid: "2",
    icon: "",
    path: "/dataBase",
    label: "基础数据",
    component: "data-base",
    isleaf: true,
  },
  {
    id: "2-3",
    pid: "2",
    icon: "",
    path: "/dataVideo",
    label: "视频集成",
    component: "data-video",
    isleaf: true,
  },

  {
    id: "7",
    pid: "0",
    icon: "xitongshezhi1",
    path: "/setting",
    label: "系统设置",
    component: "lay-set",
    isleaf: false,
  },
  {
    id: "7-1",
    pid: "7",
    icon: "xitongshezhi1",
    path: "/setting",
    label: "基础设置",
    component: "set-base",
    isleaf: true,
    index: true,
  },
  {
    id: "7-2",
    pid: "7",
    icon: "yonhu",
    path: "/setting/user",
    label: "用户管理",
    component: "set-user",
    isleaf: true,
  },
  {
    id: "7-3",
    pid: "7",
    icon: "zhandianguanli",
    path: "",
    label: "站点管理",
    isleaf: false,
  },
  {
    id: "7-3-1",
    pid: "7-3",
    icon: "",
    path: "/setting/station",
    component: "station-list",
    label: "站点列表",
    isleaf: true,
  },
  {
    id: "7-3-2",
    pid: "7-3",
    icon: "",
    path: "/setting/station_group",
    component: "station-group",
    label: "站点分组",
    isleaf: true,
  },
  {
    id: "7-3-3",
    pid: "7-3",
    icon: "",
    path: "/setting/station_online",
    component: "station-online",
    label: "在线设置",
    isleaf: true,
  },

  {
    id: "7-5",
    pid: "7",
    icon: "yuanshujuguanli1",
    path: "",
    label: "因子管理",
    component: "layout",
    isleaf: false,
  },

  {
    id: "7-5-1",
    pid: "7-5",
    icon: "",
    path: "/setting/factor_list",
    label: "因子列表",
    component: "factor-list",
    isleaf: true,
  },
  {
    id: "7-5-2",
    pid: "7-5",
    icon: "",
    path: "/setting/factor_template",
    label: "因子模板",
    component: "factor-template",
    isleaf: true,
  },
  {
    id: "7-5-3",
    pid: "7-5",
    icon: "",
    path: "/setting/factor_group",
    label: "因子分组",
    component: "factor-group",
    isleaf: true,
  },

  {
    id: "7-6",
    pid: "7",
    icon: "yuanshujuguanli1",
    path: "",
    label: "元数据管理",
    component: "layout",
    isleaf: false,
  },
  {
    id: "7-6-1",
    pid: "7-6",
    icon: "",
    path: "/setting/meta_topic",
    label: "业务主题",
    component: "set-meta-theme",
    isleaf: true,
  },
  {
    id: "7-6-2",
    pid: "7-6",
    icon: "",
    path: "/setting/meta_station_type",
    label: "站点类型",
    component: "set-meta-station",
    isleaf: true,
  },
  {
    id: "7-6-3",
    pid: "7-6",
    icon: "",
    path: "/setting/meta_station_field",
    label: "站点字段",
    component: "set-meta-field",
    isleaf: true,
  },
  {
    id: "7-6-6",
    pid: "7-6",
    icon: "",
    path: "/setting/meta_evaluate_standard",
    label: "评价标准",
    component: "set-meta-standard",
    isleaf: true,
  },
  {
    id: "7-6-4",
    pid: "7-6",
    icon: "",
    path: "/setting/meta_evaluate_factor",
    label: "评价指标",
    component: "set-meta-evalute",
    isleaf: true,
  },

  {
    id: "7-6-5",
    pid: "7-6",
    icon: "",
    path: "/setting/meta_map",
    label: "业务元数据",
    component: "set-meta-data",
    isleaf: true,
  },
];

export default menu;
